name: Build and deploy React app to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, which has read-only permission for the repository

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Build
        run: npm run build
        working-directory: ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

      - name: Create .nojekyll
        run: | 
          echo ".nojekyll" >> ./dist/.nojekyll
          git add ./dist/.nojekyll
          git commit -m "Add nojekyll"
        if: false  # not actually run in workflow, just documentation
